version: '3.7'

services:
  web:
    build: ./
    working_dir: /code/
    command:
      - /bin/bash
      - -c
      - |
        cd /code/
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code/:delegated,rw
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: starter
      POSTGRES_DB: starter
      POSTGRES_PASSWORD: starter
    restart: always
    expose:
      - "5432"
    volumes:
      - starter:/var/lib/postgresql/data

volumes:
  starter:
    external: true
