# Generated by Django 4.1.7 on 2023-04-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactusfooter",
            options={"verbose_name": "Contact Us Footer"},
        ),
    ]
