# Generated by Django 4.2.6 on 2023-10-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('common', '0004_contactusfooter_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField()),
                ('url', models.URLField(blank=True, help_text='An alternative to an internal page', null=True)),
                ('page', models.ForeignKey(blank=True, help_text='For the link/button to show, either this or the url are required', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Nav Call to Action',
            },
        ),
    ]
