# Generated by Django 4.1.7 on 2023-05-18 15:44

from django.db import migrations, models
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "author_type",
                    models.CharField(
                        choices=[("author_name", "Author name"), ("person_page", "Person page")],
                        default="author_name",
                        max_length=15,
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True, help_text="Add an author name (e.g. [first name last name])", max_length=255
                    ),
                ),
                (
                    "author_credential",
                    models.CharField(
                        blank=True,
                        help_text="Optional: Add an author credential to display alongside the author name (e.g [role, organisation])",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Author",
                "ordering": ["author_name"],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
