# Generated by Django 4.1.7 on 2023-05-19 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_articlepage_options"),
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkArticle",
            fields=[
                (
                    "articlepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog.articlepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Article",
                "verbose_name_plural": "Work Articles",
            },
            bases=("blog.articlepage",),
        ),
    ]
