# Generated by Django 5.1.5 on 2025-01-20 14:57

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
import wagtail.search.index
import wagtailmetadata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_create_homepage'),
        ('wagtailcore', '0095_query_searchpromotion_querydailyhits'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('show_contact_us_footer', models.BooleanField(default=True, help_text='Useful when u want to use the Contact Us Block for a custom contact', verbose_name='Show Contact Us Footer')),
                ('published_date', models.DateTimeField(blank=True, help_text='This date will be used for display and ordering', null=True)),
                ('content', wagtail.fields.StreamField([('rich_text', 1), ('captioned_image', 6), ('blockquote', 9)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'link', 'embed']}), 1: ('wagtail.blocks.StructBlock', [[('rich_text', 0)]], {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optimal minimum width 800px'}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional: caption text to appear below the image', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional: external link to appear below the image', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: label for the caption link, defaults to the link if left blank', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('caption_link', 4), ('caption_label', 5)]], {}), 7: ('wagtail.blocks.TextBlock', (), {}), 8: ('wagtail.blocks.TextBlock', (), {'help_text': 'Who is this quote acredited to?', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('text', 7), ('source', 8)]], {})}, null=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero Image')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'verbose_name': 'Blog Article',
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ArticleTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Article Topic',
                'verbose_name_plural': 'Article Topics',
            },
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('hero', 18), ('contact_us', 24), ('richtext', 26), ('captioned_image', 31), ('our_stack', 35)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('basic', 'Basic'), ('theme-coloured', 'Theme Coloured'), ('theme-gradient', 'Theme Coloured Gradient'), ('none', 'None')]}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h1', 'Heading 1'), ('h2', 'Heading 2'), ('h3', 'Heading 3'), ('h4', 'Heading 4')]}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Text', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('text', 3)]], {'icon': 'title', 'label': 'Simple Text'}), 5: ('wagtail.blocks.StructBlock', [[('text', 3)]], {'icon': 'title', 'label': 'Styled Text'}), 6: ('wagtail.blocks.StreamBlock', [[('simple_text', 4), ('styled_text', 5)]], {}), 7: ('wagtail.blocks.StructBlock', [[('heading', 2), ('text', 6)]], {'template': 'cms/blocks/heading_block.html'}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.CharBlock', (), {'required': False}), 10: ('wagtail.blocks.PageChooserBlock', (), {'required': True}), 11: ('wagtail.blocks.StructBlock', [[('caption', 9), ('page', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Leave blank if you wish to use the page title as a caption', 'required': False}), 14: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'For the link/button to show, either this or the url are required', 'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'help_text': 'An alternative to an internal page', 'required': False}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary')], 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('caption', 13), ('page', 14), ('url', 15), ('style', 16)]], {'required': False, 'template': 'cms/blocks/hero_block_button.html'}), 18: ('wagtail.blocks.StructBlock', [[('image', 0), ('overlay', 1), ('content', 8), ('links', 12), ('button', 17)]], {}), 19: ('wagtail.blocks.TextBlock', (), {}), 20: ('wagtail.blocks.TextBlock', (), {'label': 'Sub-Heading'}), 21: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 22: ('wagtail.blocks.EmailBlock', (), {}), 23: ('wagtail.blocks.CharBlock', (), {'label': 'Phone Number', 'max_length': 20}), 24: ('wagtail.blocks.StructBlock', [[('heading', 19), ('sub_heading', 20), ('photo', 21), ('email', 22), ('phone_number', 23)]], {}), 25: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'link', 'embed']}), 26: ('wagtail.blocks.StructBlock', [[('rich_text', 25)]], {'template': 'cms/blocks/rich_text.html'}), 27: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optimal minimum width 800px'}), 28: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional: caption text to appear below the image', 'required': False}), 29: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional: external link to appear below the image', 'required': False}), 30: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: label for the caption link, defaults to the link if left blank', 'required': False}), 31: ('wagtail.blocks.StructBlock', [[('image', 27), ('caption', 28), ('caption_link', 29), ('caption_label', 30)]], {'template': 'cms/blocks/captioned_image.html'}), 32: ('wagtail.blocks.CharBlock', (), {'required': True}), 33: ('wagtail.blocks.TextBlock', (), {'required': True}), 34: ('wagtail.blocks.StructBlock', [[('caption', 13), ('page', 14), ('url', 15), ('style', 16)]], {'required': False}), 35: ('wagtail.blocks.StructBlock', [[('heading', 32), ('content', 33), ('button', 34)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_contact_us_footer',
            field=models.BooleanField(default=True, help_text='Useful when u want to use the Contact Us Block for a custom contact', verbose_name='Show Contact Us Footer'),
        ),
        migrations.CreateModel(
            name='WorkArticle',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.articlepage')),
            ],
            options={
                'verbose_name': 'Work Article',
                'verbose_name_plural': 'Work Articles',
            },
            bases=('cms.articlepage',),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('author_name', 'Author name'), ('person_page', 'Person page')], default='author_name', max_length=15)),
                ('author_name', models.CharField(blank=True, help_text='Add an author name (e.g. [first name last name])', max_length=255)),
                ('author_credential', models.CharField(blank=True, help_text='Optional: Add an author credential to display alongside the author name (e.g [role, organisation])', max_length=255)),
                ('author_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Author',
                'ordering': ['author_name'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.author'),
        ),
        migrations.CreateModel(
            name='BlogListing',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('show_contact_us_footer', models.BooleanField(default=True, help_text='Useful when u want to use the Contact Us Block for a custom contact', verbose_name='Show Contact Us Footer')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'verbose_name': 'Blog Listing',
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ContactUsFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('sub_heading', models.TextField(verbose_name='Sub-Heading')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, null=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Contact Us Footer',
            },
        ),
        migrations.CreateModel(
            name='NavCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField()),
                ('url', models.URLField(blank=True, help_text='An alternative to an internal page', null=True)),
                ('page', models.ForeignKey(blank=True, help_text='For the link/button to show, either this or the url are required', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Nav Call to Action',
            },
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('show_contact_us_footer', models.BooleanField(default=True, help_text='Useful when u want to use the Contact Us Block for a custom contact', verbose_name='Show Contact Us Footer')),
                ('content', wagtail.fields.StreamField([('hero', 18), ('contact_us', 24), ('richtext', 25), ('anchor', 28), ('services', 35), ('clients', 40), ('work', 46)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('basic', 'Basic'), ('theme-coloured', 'Theme Coloured'), ('theme-gradient', 'Theme Coloured Gradient'), ('none', 'None')]}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h1', 'Heading 1'), ('h2', 'Heading 2'), ('h3', 'Heading 3'), ('h4', 'Heading 4')]}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Text', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('text', 3)]], {'icon': 'title', 'label': 'Simple Text'}), 5: ('wagtail.blocks.StructBlock', [[('text', 3)]], {'icon': 'title', 'label': 'Styled Text'}), 6: ('wagtail.blocks.StreamBlock', [[('simple_text', 4), ('styled_text', 5)]], {}), 7: ('wagtail.blocks.StructBlock', [[('heading', 2), ('text', 6)]], {'template': 'cms/blocks/heading_block.html'}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.CharBlock', (), {'required': False}), 10: ('wagtail.blocks.PageChooserBlock', (), {'required': True}), 11: ('wagtail.blocks.StructBlock', [[('caption', 9), ('page', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Leave blank if you wish to use the page title as a caption', 'required': False}), 14: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'For the link/button to show, either this or the url are required', 'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'help_text': 'An alternative to an internal page', 'required': False}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary')], 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('caption', 13), ('page', 14), ('url', 15), ('style', 16)]], {'required': False, 'template': 'cms/blocks/hero_block_button.html'}), 18: ('wagtail.blocks.StructBlock', [[('image', 0), ('overlay', 1), ('content', 8), ('links', 12), ('button', 17)]], {}), 19: ('wagtail.blocks.TextBlock', (), {}), 20: ('wagtail.blocks.TextBlock', (), {'label': 'Sub-Heading'}), 21: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 22: ('wagtail.blocks.EmailBlock', (), {}), 23: ('wagtail.blocks.CharBlock', (), {'label': 'Phone Number', 'max_length': 20}), 24: ('wagtail.blocks.StructBlock', [[('heading', 19), ('sub_heading', 20), ('photo', 21), ('email', 22), ('phone_number', 23)]], {}), 25: ('wagtail.blocks.RichTextBlock', (), {'template': 'service/blocks/richtext.html'}), 26: ('wagtail.blocks.CharBlock', (), {'help_text': 'The unique indentifier for this anchor', 'required': True}), 27: ('wagtail.blocks.CharBlock', (), {'help_text': 'Used on the navigation link (if used)', 'required': False}), 28: ('wagtail.blocks.StructBlock', [[('anchor_id', 26), ('name', 27)]], {}), 29: ('wagtail.blocks.TextBlock', (), {'default': 'Services', 'required': True}), 30: ('wagtail.blocks.CharBlock', (), {'required': True}), 31: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link']}), 32: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 33: ('wagtail.blocks.StructBlock', [[('heading', 30), ('description', 31), ('page', 32)]], {}), 34: ('wagtail.blocks.ListBlock', (33,), {}), 35: ('wagtail.blocks.StructBlock', [[('heading', 29), ('services', 34)]], {}), 36: ('wagtail.blocks.TextBlock', (), {'default': 'Clients', 'required': True}), 37: ('wagtail.blocks.URLBlock', (), {'required': False}), 38: ('wagtail.blocks.StructBlock', [[('website', 37), ('logo', 0)]], {}), 39: ('wagtail.blocks.ListBlock', (38,), {}), 40: ('wagtail.blocks.StructBlock', [[('heading', 36), ('clients', 39)]], {}), 41: ('wagtail.blocks.TextBlock', (), {'default': 'Our Work', 'required': True}), 42: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['cms.WorkArticle']}), 43: ('wagtail.blocks.ListBlock', (42,), {}), 44: ('wagtail.blocks.CharBlock', (), {'help_text': 'The tag/topic for filtering the content on the work page e.g. wagtail', 'required': False}), 45: ('wagtail.blocks.CharBlock', (), {'default': 'See more work', 'max_length': 100, 'required': False}), 46: ('wagtail.blocks.StructBlock', [[('heading', 41), ('work_articles', 43), ('work_topic', 44), ('show_more_caption', 45)]], {})}, null=True)),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'verbose_name': 'Service Page',
                'verbose_name_plural': 'Services Page',
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_topics', to='cms.articlepage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_article', to='cms.articletopic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='articlepage',
            name='topics',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='cms.Topic', to='cms.ArticleTopic', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='WorkListing',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('show_contact_us_footer', models.BooleanField(default=True, help_text='Useful when u want to use the Contact Us Block for a custom contact', verbose_name='Show Contact Us Footer')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'verbose_name': 'Work Listing',
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model),
        ),
    ]
