# Generated by Django 4.1.7 on 2023-05-18 12:14

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleTopic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                ("slug", models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name="slug")),
            ],
            options={
                "verbose_name": "Article Topic",
                "verbose_name_plural": "Article Topics",
            },
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="topics",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="blog.Topic",
                to="blog.ArticleTopic",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="tagged_article", to="blog.articletopic"
            ),
        ),
    ]
