# Generated by Django 4.1.7 on 2023-05-18 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
        ("blog", "0002_articletopic_alter_articlepage_topics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="author",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="team.author"
            ),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="published_date",
            field=models.DateTimeField(
                blank=True, help_text="This date will be used for display and ordering", null=True
            ),
        ),
    ]
