# Generated by Django 4.1.7 on 2023-05-19 07:41

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_articlepage_author_articlepage_published_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="content",
            field=wagtail.fields.StreamField(
                [("rich_text", wagtail.blocks.StructBlock([("rich_text", wagtail.blocks.RichTextBlock())]))],
                null=True,
                use_json_field=True,
            ),
        ),
    ]
