# Generated by Django 4.1.7 on 2023-05-19 10:31

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_articlepage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "rich_text",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "rich_text",
                                    wagtail.blocks.RichTextBlock(
                                        features=["h2", "h3", "h4", "bold", "italic", "ol", "ul", "link"]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "captioned_image",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(help_text="Optimal minimum width 800px"),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.TextBlock(
                                        help_text="Optional: caption text to appear below the image", required=False
                                    ),
                                ),
                                (
                                    "caption_link",
                                    wagtail.blocks.URLBlock(
                                        help_text="Optional: external link to appear below the image", required=False
                                    ),
                                ),
                                (
                                    "caption_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional: label for the caption link, defaults to the link if left blank",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "blockquote",
                        wagtail.blocks.StructBlock(
                            [
                                ("text", wagtail.blocks.TextBlock()),
                                (
                                    "source",
                                    wagtail.blocks.TextBlock(
                                        help_text="Who is this quote acredited to?", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
    ]
