# Generated by Django 4.1.7 on 2023-05-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_articlepage_content_alter_topic_content_object"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articlepage",
            options={"verbose_name": "Blog Article"},
        ),
    ]
