# Generated by Django 4.1.7 on 2023-04-16 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepage",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Search image",
            ),
        ),
        migrations.AddField(
            model_name="servicepage",
            name="show_contact_us_footer",
            field=models.BooleanField(
                default=True,
                help_text="Useful when u want to use the Contact Us Block for a custom contact",
                verbose_name="Show Contact Us Footer",
            ),
        ),
    ]
