# Generated by Django 4.1.7 on 2023-03-27 04:58

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page"},
        ),
        migrations.AddField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "hero",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "content",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "heading",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "heading",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("h1", "Heading 1"),
                                                                    ("h2", "Heading 2"),
                                                                    ("h3", "Heading 3"),
                                                                    ("h4", "Heading 4"),
                                                                ]
                                                            ),
                                                        ),
                                                        ("text", wagtail.blocks.TextBlock()),
                                                    ]
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                null=True,
                use_json_field=True,
            ),
        ),
    ]
