# Generated by Django 4.1.7 on 2023-04-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_homepage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="show_contact_us_footer",
            field=models.BooleanField(
                default=True,
                help_text="Useful when u want to use the Contact Us Block for a custom contact",
                verbose_name="Show Contact Us Footer",
            ),
        ),
    ]
